// node/solid/App.jsx
import { onMount } from 'solid-js'
import { DEFAULT_PAGE, resolvePage } from './pages/index.js'
import styles from './App.module.css'

export default function App(props) {
  const pageName = () => props.pageName ?? DEFAULT_PAGE
  const context = () => props.context ?? {}

  const component = () => resolvePage(pageName())

  if (import.meta.env.SSR) {
    console.info('[ssr] rendering page', pageName())
  }

  onMount(() => {
    console.info('[hydrate] props.pageName', pageName(), 'context', context())
  })

  return (
    <main class={styles.page}>
      <div class={styles.rendererLabel}>Solid Renderer</div>
      {(() => {
        const Component = component()
        return <Component context={context()} />
      })()}
    </main>
  )
}

// node/react/App.jsx
import { useEffect, useMemo } from 'react'
import { DEFAULT_PAGE, resolvePage } from './pages/index.js'
import styles from './App.module.css'

export default function App({ pageName = DEFAULT_PAGE, context = {} }) {
  const Component = useMemo(() => resolvePage(pageName), [pageName])

  useEffect(() => {
    if (typeof window !== 'undefined') {
      console.info('[hydrate] props.pageName', pageName, 'context', context)
    }
  }, [pageName, context])

  if (typeof window === 'undefined') {
    console.info('[ssr] rendering page', pageName)
  }

  return (
    <main className={styles.page}>
      <div className={styles.rendererLabel}>React Renderer</div>
      <Component context={context} />
    </main>
  )
}
