// node/solid/createApp.jsx
import { render, hydrate } from 'solid-js/web'
import App from './App.jsx'
import { DEFAULT_PAGE } from './pages/index.js'

export function createApp(pageName = DEFAULT_PAGE, context = {}) {
  let dispose = null

  return {
    app: {
      mount(target, shouldHydrate) {
        if (!target) {
          throw new Error('[reactive] mount target is required for Solid app')
        }

        if (dispose) {
          dispose()
          dispose = null
        }

        if (shouldHydrate) {
          dispose = hydrate(
            () => <App pageName={pageName} context={context} />,
            target
          )
        } else {
          target.innerHTML = ''
          dispose = render(
            () => <App pageName={pageName} context={context} />,
            target
          )
        }
      },
      unmount() {
        if (dispose) {
          dispose()
          dispose = null
        }
      },
    },
  }
}

// node/react/createApp.jsx
import { createRoot, hydrateRoot } from 'react-dom/client'
import App from './App.jsx'
import { DEFAULT_PAGE } from './pages/index.js'

export function createApp(pageName = DEFAULT_PAGE, context = {}) {
  let root = null
  let container = null

  return {
    app: {
      mount(target, hydrate) {
        if (!target) {
          throw new Error('[reactive] mount target is required for React app')
        }

        if (root) {
          root.unmount()
          root = null
        }

        container = target

        if (hydrate) {
          root = hydrateRoot(container, <App pageName={pageName} context={context} />)
        } else {
          root = createRoot(container)
          root.render(<App pageName={pageName} context={context} />)
        }
      },
      unmount() {
        if (root) {
          root.unmount()
          root = null
        }
        container = null
      },
    },
  }
}
