// node/js/pages/TestOne.vue
<template>
  <section class="test-one">
    <header>
      <h2>Counter Demo</h2>
      <p>Use the interactive counter below to verify hydration.</p>
    </header>

    <TestComponent />
  </section>
</template>

<script setup>
import TestComponent from '../components/TestComponent.vue'
</script>

<style scoped>
.test-one {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
</style>

// node/next/pages/test-one.jsx
import AppShell from '../components/AppShell.jsx'
import TestComponent from '../components/TestComponent.jsx'
import styles from './test-one.module.css'

export default function TestOnePage() {
  return (
    <AppShell>
      <section className={styles.container}>
        <header>
          <h2 className={styles.heading}>Counter Demo</h2>
          <p className={styles.lead}>Use the interactive counter below to verify hydration.</p>
        </header>

        <TestComponent />
      </section>
    </AppShell>
  )
}
